sudo: false

language: node_js

node_js:
    - 8
    - 10
    - 11
    - 12

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.npm

before_install:
    - npm config set spin false
    - npm config set progress false
    - npm install -g npm

install:
    - npm ci

script:
    - npm install . -g >/dev/null && npm uninstall . -g >/dev/null
    - mkdir -p "/tmp/$TRAVIS_REPO_SLUG" && cd "/tmp/$TRAVIS_REPO_SLUG" && npm init -y >/dev/null
    - npm install "$TRAVIS_BUILD_DIR" >/dev/null && npm uninstall "$TRAVIS_BUILD_DIR" >/dev/null
    - node -e "const czCli = require('@$TRAVIS_REPO_SLUG');"
    - cd "$TRAVIS_BUILD_DIR"

deploy:
    - provider: npm
      email: npm@whizark.com
      api_key:
          secure: G5JUJ+wny0mj5bk3PENajdMg7uzubT4CKEvNC/WXZSP+sJxu8gEs5IiYThkwWLjIjcnjx8akMZkGhaSFJFk0PHlzY7ms8pNO9TBw9AHuNdjZ3yS6mvTDQoKqixumVjfSJ5M7742casauGip/vQp9mqWupf+GOEbj08FQWmvUuaUWZAtVEV3tgobOBqK/Sc2lWU+LHCLKhr73+iA8K1e8/0QU4fRD9cWxKkf+7jLrZWoj9HAR9668EeYxv+Yw5KYby7EpRuR++1+H6EW8j6H7T5dh85/ZoK+tw81mMv7cLpXiZiN1tEpUPa7KsqFk7R1mjaHx92ukbdfexlgVzLFncbAj8DeOSIrx2LUvKmraFNAjBbG8+RLRABqQHPSKmOfkqFMZ8/m7z9hdJF7W8p1SupiAQ5S5xoec/iY6r+3XSphGzS9dpsM8u4vcG7RkbW1PwKghVC2kvyHSlalaB8nxE9uRMIA02OEfSdKnsY2hNudj4p7LsBrMoggTQnlheKC5oHp9LR/Av9MU/wL/FUAAjUQ/yggDgSCRzqY+16yGlMZCh7YCV790+R4BZ0Gd6evLqYryA2F5sAygjbJPuxDL+cvFnxKHjXS1Q2m66KcA0jEVIQTNwzabneBfQlZuQ3XwKUutV9VjhEQRhH9Y/pyNodPEbOZDZvfqf/rLhOTueqw=
      on:
          node: 12
          repo: whizark/cz-cli
          branch: master
          tags: true

notifications:
    email: false

    slack:
        rooms:
            - secure: mVxa39sKq8JS4oeVEBIb3dNH6ZL4T1z1YEkEqARmB+s0wkraMdIhiGGTpgkOeIOqXU5krPPuLC9qmjnQTegEeDQ9YMDiaF5sqZkJmuW9n3fQDZiSXsIgKxQ2ttHIaQuBwt7fNzi/kemD4WCw+QgmjvQX+QVBsNMP3aCO2/+iyjx4ZOqvrTniflbV4616XjH27B/twlbJPbWum3vReL6w0CpuOa/jtZdq+HBtlYJ/cJP3FBQekjc1e735C+lsaqCAM9Sue95t4+LnOUnXzS9Ja2zY6mg+yRrkr98CMmKzHHxZPDZz250J/948MmvbA7ebMRv52BQto8l3TgNRrU90vFdJIMYC0B85yJRx+IkMV4LX1Fq21rTtFUvontaQs1ATPb69eKNYvsXWG/I1NHJZmmCk6MLP+hp9r1UzTn1nFFB2lAfbauRCQdyXcuctvzOgyHfRKrxeVAyKcYlR7FkzCvUJ0aFut9WD+Wl/Ic10SvqUkSgI6kvGSWcOCQD91GXuVmk9N0X7N5UtcLpiAHB2IJlu3NtQqsY8+XgtWWcRI0y+GWSL8Wq64gn/iGTxUAXw8935dzXK7Yv/6LlbH1IxAuG/QW5SM6hI/rbdM1zw79/kCJBvG7iW7TZYF2w6T0j4RF9lVZhmFc5JG6XIbGDahgF8CLqJTiA9ruFCt6hJSAc=
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
